apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: uhaypjszt-go 
  janus-idp.io/tekton: uhaypjszt-go
  backstage.io/kubernetes-id: uhaypjszt-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: uhaypjszt-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  